name: CI/CD

on: [pull_request, push]

jobs:
  preflight:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Running hadolint
        uses: hadolint/hadolint-action@v3.1.0
        continue-on-error: true
        with:
          recursive: true

      - name: Running yaml lint
        uses: docker://pipelinecomponents/yamllint:0.21.1
        continue-on-error: true
        with:
          args: yamllint .

      - name: Running shellcheck
        uses: docker://pipelinecomponents/shellcheck:0.11.4
        continue-on-error: true
        with:
          args: bash -c "find . -name \*.sh -type f -print0 | xargs -0 -P $(nproc) -r -n1 shellcheck"

      - name: Running ruff
        uses: jpetrucciani/ruff-check@main
        continue-on-error: true